config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users

  root 'locations#index'
  get 'locations/about'
  get 'locations/terms'

  resources :locations
  resources :users do
    resources :reviews

  end
  resources :reviews

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user

  # has_many :images

  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  ratyrate_rater
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    if params[:name]
      @yelp = Yelp.client.search(params[:name], { term: 'food' })
    end

  end

  def show
    @review = Review.new
    @reviews = Review.all.where(location_id: params[:id])

    if @reviews.count > 0
      @score = (@reviews.sum("parking_score") + @reviews.sum("entrance_score") + @reviews.sum("table_score") +  @reviews.sum("bathroom_score"))/@reviews.all.count
      @parking_score = (@reviews.sum("parking_score"))/@reviews.all.count
      @entrance_score = (@reviews.sum("entrance_score"))/@reviews.all.count
      @bathroom_score = (@reviews.sum("bathroom_score"))/@reviews.all.count
      @table_score = (@reviews.sum("table_score"))/@reviews.all.count

    end
    if params[:id]
      @yelp = Yelp.client.business(params[:id])
    end
  end

  def create

  end

  def about
  end

  def terms
  end
  private


end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def index

  end

  def show
    if params[:id]
      @yelp = Yelp.client.business(params[:id])
    end
  end

  def create
    session[:return_to] ||= request.referer
    @review = current_user.reviews.create(review_params)
    redirect_to session.delete(:return_to)
  end

  private
  def review_params
    params.require(:review).permit(:comment,:score,:location_id,:parking_score,:entrance_score,:table_score,:bathroom_score)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobileez</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="/assets/star-rating.min.css" media="all" rel="stylesheet" />
  <script src="//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Leaflet stylesheet -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
  <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

</head>
<body>
  <nav>
    <div class="nav-wrapper grey darken-3">
      <div class="blogo">
      <a href="/" class="brand-logo"><span style="font-size:18pt">M</span><span style="font-size:22pt">0</span><span style="font-size:24pt">B</span><span style="font-size:26pt">I</span><span style="font-size:28pt">L</span><span style="font-size:32pt">E</span><span style="font-size:34pt">E</span><span style="font-size:36pt">Z</span></a>
    </div>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to 'About', locations_about_path %></li>
        <li><%= link_to 'Terms and Conditions', locations_terms_path %></li>
        <% if current_user %>
        <li><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></li>
        <% else %>
        <li><%= link_to 'Signup', new_user_registration_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div id="tagline" class="center">Find Food That's Easy to Access</div>

  <%= yield %>

  <!-- <footer class="page-footer grey darken-3">
    <%= link_to "Account Settings", edit_user_registration_path(current_user) %>
    <div class="footer-copyright">
      <div class="container">
        © 2016 Mobileez
        <a class="grey-text text-lighten-4 right" href="#!">About</a>
      </div>
    </div>
  </footer> -->

</body>
</html>

app/views/locations/about.html.erb
<div class="about">
  <h1 id="about">About</h1>

  <p>
    Mobileez is a ratings and reviews website that helps wheelchair users discover the closest, easiest-to-access places to eat out. Restaurant are rated on the accessibility of a business’s entrance and bathroom(s). Our ratings and reviews give users the freedom to confidently decide on their favorite cuisine or coffee shop, without being surprised by a missing wheelchair ramp or inaccessible toilet.
  </p>
  <p>
    The Mobileez website was created in January 2016 by General Assembly students taking a 3-month immersive course in either Product Management, Web Design, or User Experience Design.
  </p>


  <h2>Scoring Explained:</h2>
  <p>
    The stars for all four criteria are added together to give this business your Total Score. The Overall Score averages the total score from each user who has ever rated the business.
  </p>

  <h2>Ratings & Reviews - Use Your Best Judgement:</h2>
  <p>
    When rating accessibility, use your best judgement. If you are unsure how to rate something, select the closest possible answer and provide a review along with your choice.
  </p>

</div>

app/views/locations/index.html.erb
<div class="row">
  <nav>
    <div class="nav-wrapper grey darken-2">
      <%= form_tag(locations_path, method: "get", id: "search-form") do %>
      <div class="input-field col s4">
        <%= text_field_tag :name, params[:name], placeholder: "Search Locations" %>
      </div>
      <div class="input-field col s4">
        <%= submit_tag "Search", name: nil,  id:"search-button"%>
      </div>
      <% end %>
    </div>
  </nav>
</div>


<div class="row">
  <div class="col s3 grey lighten-2" height=max>
    <ul class="center-align">
      <div>
        Search Results
      </div>
      <ul class="collapsible" data-collapsible="accordion">
        <li>
          <!-- <div class="collapsible-header"></i>Search Results</div>
          <div class="collapsible-body" id="Search API results Div"> -->
          <% if @yelp %>
          <% @yelp.businesses.each do |business|%>
          <li>
            <img src="<%=business.image_url%>" alt="restaurant image" height="100" width="100" />
          </li>
          <li>
            <a href="locations/<%= business.id %>"> <%= business.name %> </a>
          </li>
          <li>
            <%= business.location.display_address[0] %> <br> <%= business.location.display_address[2] %>
          </li>

          <% end %>
          <% end %>
          <!-- </div> -->
        </li>
      </ul>
    </ul>
  </div>
  <div class="col s9 grey lighten-3" id="map">
  </div>
</div>

app/views/locations/show.html.erb
<div class="container">
<div class="row" id="businessimg">
  <div class="col s3">
    <img src="<%= @yelp.business.image_url%>" alt="restaurant image" height="250" width="250" />
  </div>

  <div class="col s8">
    <div class="row" id="top">
      <div class="col s9">
        <h4 class="bname"><%= @yelp.business.name %><h4>
        <p class="address"><%= @yelp.business.location.display_address[0] %> <br> <%= @yelp.business.location.display_address[2] %> <br> <%= @yelp.business.phone %></p>
      </div>

      <div class="col s1">
        <!-- Blue button setup-->
        <!-- Modal Trigger -->
        <div class="center">
        <a class="btn-floating waves-effect btn-small waves-light light-blue darken-1" data-target="modal1" id="modal1"class="btn modal-trigger"><i class="fa fa-question"></i></a>
        <p class="btn-content">How do we get this?</p>
      </div>

        <!-- Modal Structure -->
        <div id="modal1" class="modal modal-fixed-footer">
            <div class="modal-content">
              <h4>Modal Header</h4>
              <p>A bunch of text</p>
            </div>
            <div class="modal-footer">
              <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Close</a>
            </div>
        </div>
      </div>

      <!-- I know there's a better way to do this. I just can't figure it out right now. -->
      <div class="col s2">
        <div class="center overall">
          <% if @score %>
          <% if @score >= 15 %>
            <i class="fa fa-wheelchair fa-2x" id="excellent"></i>
              <% elsif @score < 15 && @score >= 12 %>
            <i class="fa fa-wheelchair fa-2x" id="limited"></i>
              <% elsif @score < 12 %>
            <i class="fa fa-wheelchair fa-2x" id="poor"></i>
          <%end%>
          <%end%>

          <% if @score %>
          <% if @score >= 15 %>
              <p class="promo-caption" id="excellent">Overall</p>
                <% elsif @score < 15 && @score >= 12 %>
              <p class="promo-caption" id="limited">Overall</p>
                <% elsif @score < 12 %>
              <p class="promo-caption" id="poor">Overall</p>
          <%end%>
          <% end %>

          <% if @score %>
          <% if @score >= 15 %>
            <p class="promo-rating" id="excellent"><%= @score %>/20</p>
              <% elsif @score < 15 && @score >= 12 %>
            <p class="promo-rating" id="limited"><%= @score %>/20</p>
              <% elsif @score < 12 %>
            <p class="promo-rating" id="poor"><%= @score %>/20</p>
          <%end%>
          <% end %>
        </div>
      </div>
      <div class="col s1">
        <h4></h4>
      </div>
    </div>
  </div>
</div>


      <div class="row" id="promosection">
        <div class="col s3">
          <div class="center promo">
            <i class="fa fa-cutlery fa-2x"></i>
            <p class="promo-caption">Table</p>
            <p class="promo-rating"><%= @table_score %>/5</p>
          </div>
        </div>
        <div class="col s3">
          <div class="center promo">
            <i class="fa fa-wheelchair fa-2x"></i>
            <p class="promo-caption">Ramp</p>
            <p class="promo-rating"><%= @entrance_score %>/5</p>
          </div>
        </div>
        <div class="col s3">
          <div class="center promo">
            <i class="fa fa-car fa-2x"></i>
            <p class="promo-caption">Parking</p>
            <p class="promo-rating"><%= @parking_score %>/5</p>
          </div>
        </div>
        <div class="col s3">
          <div class="center promo">
            <i class="fa fa-venus-mars fa-2x"></i>
            <p class="promo-caption">Restrooms</p>
            <p class="promo-rating"><%= @bathroom_score %>/5</p>
          </div>
        </div>

      </div>
      <div class="wrap">
        <a class="waves-effect button grey lighten-1" href="#reviewb">WRITE A REVIEW</a>
        <a class="waves-effect button grey lighten-1" href="#">FAVORITE</a>
      </div>
      <ul class="center" id="menu">
        <li><a href="#collectionbox">Reviews</a></li>
        <li><a href="#">Description</a></li>
      </ul>
  </div>
</div>


<% if @score %>
<% if @score >= 15 %>
<i class="fa fa-wheelchair fa-3x" id="excellent">Excellent Accessibility</i>
<% elsif @score < 15 && @score >= 12 %>
<i class="fa fa-wheelchair fa-3x" id="limited">Limitied Accessibility</i>
<% elsif @score < 12 %>
<i class="fa fa-wheelchair fa-3x" id="poor">Poor Accessibility</i>
  <%end%>
  <% end %>
<a name="reviewb"></a>
<div class="reviewbox">
<% if current_user %>
  <%= form_for [@review] do |f| %>

    <div class="form-group">
    <%= f.label :table_score %>
    <%= f.range_field :table_score, in: 1..5, class:"rating",id:"input-1", data: {min:"0", max:"5", step:"1"}%>
    <%= f.label :entrance_score %>
    <%= f.range_field :entrance_score, in: 1..5, class:"rating",id:"input-2", data: {min:"0", max:"5", step:"1"}%>
    <%= f.label :parking_score %>
    <%= f.range_field :parking_score, in: 1..5, class:"rating",id:"input-3", data: {min:"0", max:"5", step:"1"}%>
    <%= f.label :bathroom_score %>
    <%= f.range_field :bathroom_score, in: 1..5, class:"rating",id:"input-4", data: {min:"0", max:"5", step:"1"}%>
    <%= f.hidden_field :location_id, value: @yelp.business.id %>
    </div>
    <div class="form-group">
      <%= f.text_area :comment, placeholder: "Write a review...", :id => "comment_area" %>
    </div>
    <%= f.submit%>
  <%end%>
<%end%>
</div>

<a name="collectionbox"></a>
<ul class="collection">
  <%@reviews.each do |review| %>
    <li class="collection-item avatar">
      <i class="fa fa-user fa-2x"></i>
      <p><%=review.comment %></p><br>
      Total: <%=review.table_score + review.entrance_score + review.parking_score + review.bathroom_score %>/20 <br>
      Table: <%=review.table_score %>/5 <br>
      Entry: <%=review.entrance_score %>/5 <br>
      Parking: <%=review.parking_score %>/5 <br>
      Bathroom: <%=review.bathroom_score %>/5 <br>
    </li>
  <%end%>
</ul>
</div>

app/views/reviews/_review.html.erb
<div class="review clearfix">
	<div class="review_content">
		<p class="review_name"><strong><%= review.name %></strong></p>
		<p class="review_body"><%= review.body %></p>
		<p class="review_time"><%= time_ago_in_words(review.created_at) %> Ago</p>
	</div>

	<% if user_signed_in? %>
	<p><%= link_to 'Delete', [review.location, review],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %></p>
 	<% end %>
</div>